site_name: Tutorial K3s
plugins:
  - search

nav:
  - Início: index.md
  - Configurações básicas:
      - Orange Pi: basics/orangepi.md
      - Raspberry Pi:
        - Raspberry Pi OS: basics/raspberry/raspberrypi_os.md
        - Ubuntu Server [Extra]: basics/raspberry/ubuntu_server.md
  - Cluster de alta performance:
      - Configurações: hpc/configs.md
      - Instalações:
          - OpenMPI: hpc/open_mpi.md
          - Python: hpc/python_lang.md
          - R: hpc/r_lang.md
      - Testes: hpc/tests.md
      - SLURM:
          - Comandos básicos: hpc/slurm.md
  - Cluster com balanceamento de carga:
      - Básico K3s: lbc/basic_k3s.md
      - Comandos básicos: lbc/commands.md
      - Manifestos:
        - Arquivos:
          - "Panda Web": lbc/files/pandaweb.md
          - "Rancher Demo": lbc/files/rancherdemo.md
        - Configuração: lbc/manifests.md
      - Traefik [Extra]: lbc/traefik.md
  - Referências: references.md

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  language: pt
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: amber
extra:
  social:
    - icon: material/github
      link: https://github.com/Prisma-IAP
